### PR TITLE
Fix compilation error.

### PR DESCRIPTION
**Pull request by mikapfl**
# Purpose of this PR
Fix compilation error introduced in #1113 due to missing value in declaration.

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
My bad.  I tested a proper run, but not the test.

**Comment by mikapfl** [comment]
Nono, I would like to own this error, I didn't test the PR before merging, which is my responsibility as the owner of the PR. After travelling yesterday with deutsche bahn I would like to cite them:

> We apologize for *any* inconvenience.
